[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.regex]
target = "functions/state_events.lua"
pattern = "^(.*)hand_chips\\*mult(.*)$"
position = "at"
payload = '''$1 G.FUNCS.calculate_round_score(hand_chips, mult) $2'''
match_indent = true
overwrite = true
times = 999999

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "G.ARGS.score_intensity.earned_score = G.GAME.current_round.current_hand.chips*G.GAME.current_round.current_hand.mult"
position = "before"
payload = '''--[['''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "G.ARGS.score_intensity.earned_score = G.GAME.current_round.current_hand.chips*G.GAME.current_round.current_hand.mult"
position = "after"
payload = ''']]--
G.ARGS.score_intensity.earned_score = G.FUNCS.calculate_round_score(G.GAME.current_round.current_hand.chips, G.GAME.current_round.current_hand.mult)
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.T, config={text = "X", lang = G.LANGUAGES['en-us'], scale = scale*2, colour = G.C.UI_MULT, shadow = true}},'''
position = "at"
payload = '''
{n=G.UIT.T, config={ref_table = G, ref_value = 'operation_title', scale = scale*2, colour = G.C.UI_MULT, shadow = true, func = 'get_operation_title'}}
'''
match_indent = true
times = 1
overwrite = true